apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conductor-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: knor

  source:
    repoURL: https://github.com/HammadTariq14/gitops
    targetRevision: main
    path: charts/app
    helm:
      valueFiles:
        - /apps/conductor/values.yaml
        - /apps/conductor/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: conductor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
